$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: sklearn-custom-env
build:
  dockerfile:
    base_image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest
conda_file:
  dependencies:
    - python=3.10
    - pip
    - pip:
        - numpy==1.26.4
        - scikit-learn==1.3.2
        - joblib
        - azureml-inference-server-http
