$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: sklearn-custom-env
build:
  dockerfile:
    base_image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest
conda_file:
  channels:
    - conda-forge
  dependencies:
    - python=3.10
    - numpy=2.2.6
    - scikit-learn=1.7.2
    - pip
    - pip:
        - joblib
        - azureml-inference-server-http
