$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: sklearn-env
version: 1
description: Environment for sklearn training
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest
conda_file: conda.yml
