$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: sample-endpoint
model: azureml:sample-model:8
environment:
  file: ../environment.yml
code_configuration:
  code: ../src
  scoring_script: score.py
instance_type: Standard_D2a_v4
instance_count: 1
