$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: sample-endpoint
model: azureml:sample-ml-model:1
environment: azureml:AzureML-sklearn-1.0-ubuntu20.04-py38-cpu@latest
code_configuration:
  code: ./src
  scoring_script: score.py
instance_type: Standard_DS3_v2
instance_count: 1
